default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: check-merge-conflict
      - id: end-of-file-fixer

  # This should be before auto-providers to ensure that the yaml file is correct
  # - repo: https://github.com/adrienverge/yamllint.git
  #   rev: v1.34.0
  #   hooks:
  #     - id: yamllint
  #       pass_filenames: false
  #       args: [--strict, -f, colored, -c, .yamllint.yml, .]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.5
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        # args: [odoo_graphql, --fix]
      # Run the formatter.
      - id: ruff-format
  # Do not use cache to prevent conflict on pipeline
  # https://github.com/python-poetry/poetry/issues/8189
  # - repo: https://github.com/python-poetry/poetry
  #   rev: '1.6.0'  # add version here
  #   hooks:
  #     - id: poetry-check
  #       args: [--no-cache]
  #       language_version: python3.9
  #     - id: poetry-lock
  #       args: [--no-cache]
  #       language_version: python3.9

  # - repo: https://github.com/python-poetry/poetry-plugin-export
  #   rev: '1.6.0'  # add version here
  #   hooks:
  #     - id: poetry-export
  #       args: ["--no-cache", "-f", "requirements.txt", "-o", "requirements.txt"]

